---
title:               Obtvse Demo
tagline:             Clever tagline.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Kyle S. Goodwin
twitter:             reluthan
github:              goodwink
email:               goodwink+blog@gmail.com
google_analytics_id: YOUR_GA_ID